import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Header from "./components/header"
import Footer from "./components/footer"
import { AppProvider } from "@/app/context/appContext"
import { ApolloProviderWrapper } from "@/app/context/ApolloProviderWrapper"
import ReactQueryProvider from "./context/QueryClientProvider"; // Assure-toi que le chemin est correct

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AppProvider>
        <ApolloProviderWrapper>
          <ReactQueryProvider>
            <Header />
            {children}
            <Footer />
          </ReactQueryProvider> 
        </ApolloProviderWrapper>
      </AppProvider>
      </body>
    </html>
  );
}
